discarding /n/home13/azhou/.conda/envs/mypython/bin from PATH
prepending /n/home13/azhou/.conda/envs/mypython/bin to PATH
Using TensorFlow backend.
Traceback (most recent call last):
  File "src/train-wonderland-4.py", line 40, in <module>
    model.add(LSTM(256, input_shape=(X.shape[1], X.shape[2]), return_sequences=True))
  File "/n/home13/azhou/.conda/envs/mypython/lib/python2.7/site-packages/keras/models.py", line 292, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/n/home13/azhou/.conda/envs/mypython/lib/python2.7/site-packages/keras/engine/topology.py", line 374, in create_input_layer
    self(x)
  File "/n/home13/azhou/.conda/envs/mypython/lib/python2.7/site-packages/keras/engine/topology.py", line 517, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/n/home13/azhou/.conda/envs/mypython/lib/python2.7/site-packages/keras/engine/topology.py", line 571, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/n/home13/azhou/.conda/envs/mypython/lib/python2.7/site-packages/keras/engine/topology.py", line 155, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/n/home13/azhou/.conda/envs/mypython/lib/python2.7/site-packages/keras/layers/recurrent.py", line 227, in call
    input_length=input_shape[1])
  File "/n/home13/azhou/.conda/envs/mypython/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1318, in rnn
    axes = [1, 0] + list(range(2, len(outputs.get_shape())))
  File "/n/sw/fasrcsw/apps/Core/tensorflow/20160511-fasrc02/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 462, in __len__
    raise ValueError("Cannot take the length of Shape with unknown rank.")
ValueError: Cannot take the length of Shape with unknown rank.
